# Generated by Django 3.2.6 on 2021-12-10 08:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broiler',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='broiler',
            name='animal_bedding',
        ),
        migrations.AddField(
            model_name='account',
            name='organization_name',
            field=models.CharField(default='TEST COMPANY', max_length=30),
        ),
        migrations.AddField(
            model_name='broiler',
            name='animal_bedding_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 9, 44, 13, 61554)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broiler',
            name='color',
            field=models.CharField(default='white', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broiler',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 9, 44, 48, 177928)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broiler',
            name='gender',
            field=models.CharField(default='male', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_concluded', models.BooleanField(default=False)),
                ('broilers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='api.broiler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_weeks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
