MAX_WEIGHT = 2.4
MIN_WEIGHT = [1.0, 1.3]
MAX_REDUCTION_IN_WEIGHT_PERCENTAGE = 20.0
MIN_INCREMENT_IN_WEIGHT_PERCENTAGE = 20.0

MAX_FEED_CONSUMABLE = 7.0
MIN_FEED_CONSUMABLE = 4.0
MAX_REDUCTION_IN_FEED_PERCENTAGE = 20.0
MIN_INCREMENT_IN_FEED_PERCENTAGE = 20.0

MAX_TEMPERATURE = 30.0
MIN_TEMPERATURE = 21.0
MAX_REDUCTION_IN_TEMPERATURE_PERCENTAGE = 20.0
MIN_INCREMENT_IN_TEMPERATURE_PERCENTAGE = 20.0

MAX_WEEKS_FOR_ANIMAL_BEDDING = 2
